name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change this to your desired AWS region

      - name: Install AWS CLI (Windows)
        run: |
          Invoke-WebRequest -Uri https://awscli.amazonaws.com/AWSCLIV2.msi -OutFile C:\AWSCLIV2.msi
          Start-Process msiexec -Wait -ArgumentList '/i C:\AWSCLIV2.msi /quiet'
          Remove-Item -Path C:\AWSCLIV2.msi

      - name: Deploy to EC2
        run: |
          # Replace 'your-ec2-instance-ip' with the public IP address or DNS name of your EC2 instance
          # Replace 'path/to/your/app' with the path to your application files on the EC2 instance
          # Replace 'your-app-start-command' with the command to start your application
          ssh -i "path/to/your/private-key.pem" ec2-user@your-ec2-instance-ip "cd path/to/your/app && git pull origin main && your-app-start-command"
